apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: kube-system
spec:
  containers:
  - name: debug
    image: nicolaka/netshoot:latest
    command: ["sleep", "infinity"]
    stdin: true
    tty: true
  restartPolicy: Never
