apiVersion: v1
kind: ServiceAccount
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::211125331032:role/ip-throttle-webhook'
---
apiVersion: v1
kind: Service
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: ip-throttle-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-throttle-webhook
  template:
    metadata:
      labels:
        app: ip-throttle-webhook
    spec:
      serviceAccountName: ip-throttle-webhook
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - name: webhook
          image: 211125331032.dkr.ecr.eu-west-1.amazonaws.com/test:latest
          imagePullPolicy: Always
          env:
            - name: THROTTLE_AT_PERCENT
              value: '10'
            - name: LOG_LEVEL
              value: 'INFO'
            - name: AWS_REGION
              value: 'eu-west-1'
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: 'regional'
            - name: AWS_EC2_METADATA_DISABLED
              value: 'true'
            - name: DRY_MODE
              value: 'true'
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: cert
              mountPath: /certs
              readOnly: true
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: ip-throttle-webhook-tls
        - name: aws-iam-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ip-throttle-webhook
webhooks:
  - name: throttle.ip.karpenter.aws
    rules:
      - operations: ['CREATE']
        apiGroups: ['karpenter.sh']
        apiVersions: ['v1']
        resources: ['nodeclaims']
    clientConfig:
      service:
        name: ip-throttle-webhook
        namespace: kube-system
        path: '/validate'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVSUJ5N2ExZVpXNEYwdUlIL05HdXlUQm1hakwwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xqRXNNQ29HQTFVRUF3d2phWEF0ZEdoeWIzUjBiR1V0ZDJWaWFHOXZheTVyZFdKbExYTjVjM1JsYlM1egpkbU13SGhjTk1qVXdOVEl4TURVek1qQTFXaGNOTWpZd05USXhNRFV6TWpBMVdqQXVNU3d3S2dZRFZRUUREQ05wCmNDMTBhSEp2ZEhSc1pTMTNaV0pvYjI5ckxtdDFZbVV0YzNsemRHVnRMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtRNThIVXdSakVIZFV2TVRERjZ2UFh0NG0rbzF3WFJRTWNoRzVpTwpGRkd2VzhTQ28zajdsT1VVYzNSUDAwOXdSQ0k0VGZLb3FzVUc5MDlJZVNyc2Z2T2tudGNaTklXbThXelpySFdZCjNGd2RmZks4bkR3QkhVNjVSTndzMXBwYmJ3a3RxTmQ4d28yK3daVTdnb1N6VlA1b1Ywb3dWMTRrbEpiODRZUWYKZ240Y1V3OXUwOXh2c2E2ZFEyZ3Z2WGMvbnhQUUZEZW9YcEpvWmZrcVQ4TzVPV3NvNDEra3dQbnp3QkhWUkdVTgpIQkV2RERoeVVwL2dpR001cmdSYmZQVDBtejUyL2t2OGNmUkNrRHk0dFlqc2t1Z0RiSkxseDQycnlKYmNLUWRDClVmZi9NSjJEb1lFcU83NWpiWDBpZnNUUWpSVW1FS1RjL1FkaE9sWG43T2RweFdVQ0F3RUFBYU9CMHpDQjBEQWQKQmdOVkhRNEVGZ1FVYUoxZ0FEeHVoUmxObUFyYnh0UC91ekkwUjdnd0h3WURWUjBqQkJnd0ZvQVVhSjFnQUR4dQpoUmxObUFyYnh0UC91ekkwUjdnd1lRWURWUjBSQkZvd1dJSWphWEF0ZEdoeWIzUjBiR1V0ZDJWaWFHOXZheTVyCmRXSmxMWE41YzNSbGJTNXpkbU9DTVdsd0xYUm9jbTkwZEd4bExYZGxZbWh2YjJzdWEzVmlaUzF6ZVhOMFpXMHUKYzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3Q3dZRFZSMFBCQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRgpCd01CTUFrR0ExVWRFd1FDTUFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKL0VyS2szRkp4ZEM2V0JZT0plCnJybUlGbG5PcHlSRDBsNndZcVAyblhPTUFzb0dIZkhzRUUrd1BuQkUyLzBBS0RrbXUxK0N1YklmSG9ROStzMkoKenlmbXRHbnNIdVJKbzRHWVA2UGdTY09LY3VuVUZJZEp3bjZFeVhZQ1RqRHF3WGpYaFZIR3F5MVJKUUlOdVBLZApPLzdVSml2ekZtTjgzc3E4SHRMWEt1MXk1bHBrZlk3MXVCMW1CZ1BmYlNQZW5rRTJtTG04YzJjdTNuZC9Ya2trCnFlZVVmanQ0Qktla3UwUXo4T1pRSWhnalIweHBGbGxLMmFCYmtBZ21NU1pjQmhqM3BHN2JNaXRZMy9LSmhBSDIKbXBUNzkwVTNUWWlpWW5pU0V5RXZESU1xOExCNS9obmRaRzhNc3Y4RlNndUw0NTVvR3JwZEhiY3orNEsvWGNIMgpmYkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ['v1']
    sideEffects: None
    namespaceSelector: {}  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-throttle-webhook
rules:
  - apiGroups: ["karpenter.k8s.aws"]
    resources: ["ec2nodeclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ip-throttle-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ip-throttle-webhook
subjects:
  - kind: ServiceAccount
    name: karpenter
    namespace: kube-system