apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::211125331032:role/ip-throttle-webhook'
---
apiVersion: v1
kind: Service
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: ip-throttle-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-throttle-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-throttle-webhook
  template:
    metadata:
      labels:
        app: ip-throttle-webhook
    spec:
      serviceAccountName: ip-throttle-webhook
      containers:
        - name: webhook
          image: your-registry/ip-throttle-webhook:latest
          env:
            - name: THROTTLE_AT_PERCENT
              value: '10'
            - name: LOG_LEVEL
              value: 'DEBUG'
            - name: AWS_REGION
              value: 'eu-west-1'
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: cert
              mountPath: /certs
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: ip-throttle-webhook-tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ip-throttle-webhook
webhooks:
  - name: throttle.ip.karpenter.aws
    rules:
      - operations: ['CREATE']
        apiGroups: ['karpenter.sh']
        apiVersions: ['v1']
        resources: ['nodeclaims']
    clientConfig:
      service:
        name: ip-throttle-webhook
        namespace: kube-system
        path: '/validate'
      caBundle: <CA_BUNDLE>
    admissionReviewVersions: ['v1']
    sideEffects: None
